#pragma once

/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <userver/storages/postgres/query.hpp>

namespace sql {

// Generated from: src/sql/add_object.sql
extern const userver::storages::postgres::Query add_object;

// Generated from: src/sql/get_all.sql
extern const userver::storages::postgres::Query get_all;

// Generated from: src/sql/group_by_time.sql
extern const userver::storages::postgres::Query group_by_time;

} // namespace sql
